In [1]:
import requests
from bs4 import BeautifulSoup

html_doc = requests.get('https://www.worldometers.info/coronavirus/')
soup = BeautifulSoup(html_doc.content, 'html.parser')

table_content = soup.find('table')
table_head = table_content.find('thead')
table_body = table_content.find('tbody')
table_row = table_body.find_all('tr')

In [7]:
cells = table_row[8].find_all('td')

for i in range(len(cells)):
    print(i, ":", cells[i].text.strip())

0 : 1
1 : USA
2 : 111,820,082
3 :
4 : 1,219,487
5 :
6 : 109,814,428
7 :
8 : 786,167
9 : 940
10 : 333,985
11 : 3,642
12 : 1,186,851,502
13 : 3,544,901
14 : 334,805,269
15 : North America
16 : 3
17 : 275
18 : 0
19 :
20 :
21 : 2,348

In [3]:
import os

In [12]:
file = open("worldmeters.csv", "w", encoding="utf-8")

# Write headers
header_list = [
    "Country",
    "Total Cases",
     "New Cases",
    "Total Deaths",
     "New deaths",
    "Total Recovered",
     "New recovered",
     "Active cases",
     "serious/critical",
    "Tot Cases/1M pop",
     "Deaths/1M pop",
    "Total Tests",
     "Tests/1M pop",
    "Population",
     "Case evry X ppl",
    "Death evry X ppl",
    "Test evry X ppl",
     "New cases/1m pop",
     "New Deaths/1m pop",
     "Active cases/1m pop",
     
]

file.write(",".join(header_list))
file.write("\n")

# Loop through countries
for row in table_row[8:]:

    cells = row.find_all("td")
    
    row_data = []

    row_data.append(cells[1].text.strip())   # Country
    row_data.append(cells[2].text.strip())   # Total Cases
    row_data.append(cells[3].text.strip())   # New Cases
    row_data.append(cells[4].text.strip())   # Total Deaths
    row_data.append(cells[5].text.strip())   # New Deaths
    row_data.append(cells[6].text.strip())   # Total Recovered
    row_data.append(cells[7].text.strip())   # New Recovered
    row_data.append(cells[8].text.strip())   # Active Cases
    row_data.append(cells[9].text.strip())   # Serious/Critical
    row_data.append(cells[10].text.strip())  # Total Cases/1M pop
    row_data.append(cells[11].text.strip())  # Deaths/1M pop
    row_data.append(cells[12].text.strip())  # Total Tests
    row_data.append(cells[13].text.strip())  # Tests/1M pop
    row_data.append(cells[14].text.strip())  # Population
    row_data.append(cells[16].text.strip())  # Continent
    row_data.append(cells[17].text.strip())  # 1 Case every X ppl
    row_data.append(cells[18].text.strip())  # 1 Death every X ppl
    row_data.append(cells[19].text.strip())  # 1 Test every X ppl
    row_data.append(cells[20].text.strip())  # New Cases/1M pop
    row_data.append(cells[21].text.strip())  # New Deaths/1M pop


    #file.write(",".join(row_data))
    #file.write("\n")
    #the problem is here excel is finding  the numbers too big open with sheets cant etend on this comp
    file.write('"' + '","'.join(row_data) + '"')
    file.write("\n")
file.close()

In [16]:
import pandas as pd

In [18]:
df = pd.read_csv("worldmeters.csv")

In [23]:
print(df[["Country", "Active cases"]])

            Country Active cases
0               USA      786,167
1             India          NaN
2            France            0
3           Germany      405,368
4            Brazil    1,783,377
..              ...          ...
226         Tokelau           80
227    Vatican City            0
228  Western Sahara            0
229      MS Zaandam            0
230           China      118,977

[231 rows x 2 columns]

In [25]:
df

,Country,Total Cases,New Cases,Total Deaths,New deaths,Total Recovered,New recovered,Active cases,serious/critical,Tot Cases/1M pop,Deaths/1M pop,Total Tests,Tests/1M pop,Population,Case evry X ppl,Death evry X ppl,Test evry X ppl,New cases/1m pop,New Deaths/1m pop,Active cases/1m pop
0,USA,"111,820,082",NaN,"1,219,487",NaN,"109,814,428",NaN,"786,167",940.0,"333,985","3,642","1,186,851,502","3,544,901","334,805,269",3,275,0.0,NaN,NaN,"2,348"
1,India,"45,035,393",NaN,"533,570",NaN,NaN,NaN,NaN,NaN,"32,016",379,"935,879,495","665,334","1,406,631,776",31,"2,636",2.0,NaN,NaN,0.4
2,France,"40,138,560",NaN,"167,642",NaN,"39,970,918",NaN,0,NaN,"612,013","2,556","271,490,188","4,139,547","65,584,518",2,391,0.0,NaN,NaN,NaN
3,Germany,"38,828,995",NaN,"183,027",NaN,"38,240,600",NaN,"405,368",NaN,"462,891","2,182","122,332,384","1,458,359","83,883,596",2,458,1.0,NaN,NaN,"4,833"
4,Brazil,"38,743,918",NaN,"711,380",NaN,"36,249,161",NaN,"1,783,377",NaN,"179,908","3,303","63,776,166","296,146","215,353,593",6,303,3.0,NaN,NaN,"8,281"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Tokelau,80,NaN,NaN,NaN,NaN,NaN,80,NaN,"58,055",NaN,NaN,NaN,"1,378",17,NaN,NaN,NaN,NaN,"58,055"
227,Vatican City,29,NaN,NaN,NaN,29,NaN,0,NaN,"36,295",NaN,NaN,NaN,799,28,NaN,NaN,NaN,NaN,NaN
228,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,16,2,NaN,NaN,"626,161","62,616","626,161",NaN,NaN,NaN,NaN
229,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,347,4,"160,000,000","110,461","1,448,471,400","2,878","274,748",9.0,NaN,NaN,82

In [26]:
df.columns

Index(['Country', 'Total Cases', 'New Cases', 'Total Deaths', 'New deaths',
       'Total Recovered', 'New recovered', 'Active cases', 'serious/critical',
       'Tot Cases/1M pop', 'Deaths/1M pop', 'Total Tests', 'Tests/1M pop',
       'Population', 'Case evry X ppl', 'Death evry X ppl', 'Test evry X ppl',
       'New cases/1m pop', 'New Deaths/1m pop', 'Active cases/1m pop'],
      dtype='object')

In [28]:
print(df.dtypes)

Country                 object
Total Cases             object
New Cases              float64
Total Deaths            object
New deaths             float64
Total Recovered         object
New recovered          float64
Active cases            object
serious/critical       float64
Tot Cases/1M pop        object
Deaths/1M pop           object
Total Tests             object
Tests/1M pop            object
Population              object
Case evry X ppl         object
Death evry X ppl        object
Test evry X ppl        float64
New cases/1m pop       float64
New Deaths/1m pop      float64
Active cases/1m pop     object
dtype: object

In [31]:
df["Active cases"] = pd.to_numeric( df["Active cases"].str.replace(",", ""), errors="coerce")

In [33]:
df[df["Active cases"] > 1000000]

,Country,Total Cases,New Cases,Total Deaths,New deaths,Total Recovered,New recovered,Active cases,serious/critical,Tot Cases/1M pop,Deaths/1M pop,Total Tests,Tests/1M pop,Population,Case evry X ppl,Death evry X ppl,Test evry X ppl,New cases/1m pop,New Deaths/1m pop,Active cases/1m pop
4,Brazil,"38,743,918",NaN,"711,380",NaN,"36,249,161",NaN,1783377.0,NaN,"179,908","3,303","63,776,166","296,146","215,353,593",6,303,3.0,NaN,NaN,"8,281"

In [43]:
df[
    (df["Country"].str.contains("a", case=False)) &
    (df["Country"].str.contains("z", case=False))
]

,Country,Total Cases,New Cases,Total Deaths,New deaths,Total Recovered,New recovered,Active cases,serious/critical,Tot Cases/1M pop,Deaths/1M pop,Total Tests,Tests/1M pop,Population,Case evry X ppl,Death evry X ppl,Test evry X ppl,New cases/1m pop,New Deaths/1m pop,Active cases/1m pop
4,Brazil,"38,743,918",NaN,"711,380",NaN,"36,249,161",NaN,1783377.0,NaN,"179,908","3,303","63,776,166","296,146","215,353,593",6,303,3.0,NaN,NaN,"8,281"
33,Czechia,"4,759,041",NaN,"43,517",NaN,"4,715,206",NaN,318.0,2.0,"443,246","4,053","57,834,241","5,386,552","10,736,784",2,247,0.0,NaN,NaN,30
35,Switzerland,"4,453,053",NaN,"14,452",NaN,"4,438,309",NaN,292.0,NaN,"507,549","1,647","23,833,472","2,716,487","8,773,637",2,607,0.0,NaN,NaN,33
43,New Zealand,"2,621,111",NaN,"5,697",NaN,"2,613,791",NaN,1623.0,NaN,"535,117","1,163","7,768,604","1,586,011","4,898,203",2,860,1.0,NaN,NaN,331
55,Kazakhstan,"1,411,831",NaN,"13,848",NaN,"1,383,020",NaN,14963.0,24.0,"73,514",721,"11,575,012","602,707","19,205,043",14,"1,387",2.0,NaN,NaN,779
77,Azerbaijan,"835,234",NaN,"10,400",NaN,"824,089",NaN,745.0,NaN,"81,089","1,010","7,748,050","752,223","10,300,205",12,990,1.0,NaN,NaN,72
87,Venezuela,"552,695",NaN,"5,856",NaN,"546,537",NaN,302.0,31.0,"18,885",200,"3,359,014","114,771","29,266,991",53,"4,998",9.0,NaN,NaN,10
95,Bosnia and Herzegovina,"403,615",NaN,"16,388",NaN,"379,084",NaN,8143.0,NaN,"124,215","5,044","1,884,721","580,036","3,249,317",8,198,2.0,NaN,NaN,"2,506"
99,Zambia,"349,304",NaN,"4,069",NaN,"341,316",NaN,3919.0,NaN,"17,940",209,"4,112,961","211,244","19,470,234",56,"4,785",5.0,NaN,NaN,201
107,Zimbabwe,"266,359",NaN,"5,740",NaN,"258,888",NaN,1731.0,12.0,"17,373",374,"2,525,756","164,744","15,331,428",58,"2,671",6.0,NaN,NaN,113
108,Uzbekistan,"253,662",NaN,"1,637",NaN,"241,486",NaN,10539.0,23.0,"7,378",48,"1,377,915","40,077","34,382,084",136,"21,003",25.0,NaN,NaN,307
110,Mozambique,"233,731",NaN,"2,250",NaN,"228,805",NaN,2676.0,11.0,"7,064",68,"1,371,127","41,437","33,089,461",142,"14,706",24.0,NaN,NaN,81
114,Kyrgyzstan,"206,897",NaN,"2,991",NaN,"196,406",NaN,7500.0,131.0,"30,750",445,"1,907,195","283,460","6,728,271",33,"2,250",4.0,NaN,NaN,"1,115"
155,Tanzania,"43,223",NaN,846,NaN,NaN,NaN,NaN,NaN,683,13,NaN,NaN,"63,298,550","1,464","74,821",NaN,NaN,NaN,667
229,MS Zaandam,9,NaN,2,NaN,7,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN